name: CI Pipeline

# Executar quando houver push ou rodar manualmente
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout do repositório
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Teste simples (echo)
    - name: Testes unitários
      run: echo "Executando testes unitários"

    # Step 3: Testes de integração (echo)
    - name: Testes de integração
      run: echo "Executando testes de integração"

    # Step 4: Testes funcionais (echo)
    - name: Testes funcionais
      run: echo "Executando testes funcionais"

    # Step 5: Testes de carga (echo)
      run: echo "Executando testes de carga"
git add .
git commit -m "Adicionar pipeline básico"
git push
