- name: Testes unitários
  run: echo "Executando testes unitários"

- name: Testes de integração
  run: echo "Executando testes de integração"

- name: Testes funcionais
  run: echo "Executando testes funcionais"

- name: Testes de carga
  run: echo "Executando testes de carga"
- name: SonarQube Scan
  uses: sonarsource/sonarcloud-github-action@v1.10

  with:
    projectBaseDir: ./
    args: >
      -Dsonar.projectKey=<seu-projeto>
      -Dsonar.organization=<sua-org>
      -Dsonar.sources=.

- name: Snyk Security Scan
  uses: snyk/actions@master
  with:
    args: test
  env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

- name: Snyk Security Scan
  uses: snyk/actions@master
  with:
    args: test
  env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

git add .
git commit -m "Adicionei steps e integração com SonarQube e Snyk"
git push origin <sua-branch>
